import { PrismaClient } from "@prisma/client";
import { PrismaPg } from "@prisma/adapter-pg";
import { Pool } from "pg";
import bcrypt from "bcryptjs";
import { generateUniqueSlug } from "../src/lib/slug";

const pool = new Pool({ connectionString: process.env.DATABASE_URL });
const adapter = new PrismaPg(pool);
const prisma = new PrismaClient({ adapter });

const properties = [
  {
    title: "The Glass Pavilion",
    address: "Beverly Hills, California",
    city: "Beverly Hills",
    price: 5250000,
    priceType: "sale",
    beds: 5,
    baths: 4.5,
    sqm: 4200,
    type: "Villa",
    status: "FOR SALE",
    badge: "Exclusive",
    imageUrl: "https://images.unsplash.com/photo-1600596542815-ffad4c1539a9?w=800&q=80",
    imageAlt: "Luxury modern villa exterior with pool",
    isFeatured: true,
  },
  {
    title: "Azure Heights Penthouse",
    address: "Downtown, Vancouver",
    city: "Vancouver",
    price: 3800000,
    priceType: "sale",
    beds: 3,
    baths: 3,
    sqm: 2100,
    type: "Penthouse",
    status: "FOR SALE",
    badge: "New Arrival",
    imageUrl: "https://images.unsplash.com/photo-1560448204-e02f11c3d0e2?w=800&q=80",
    imageAlt: "Modern interior living room with panoramic view",
    isFeatured: true,
  },
  {
    title: "Modern Family Home",
    address: "123 Pine St, Seattle",
    city: "Seattle",
    price: 850000,
    priceType: "sale",
    beds: 3,
    baths: 2,
    sqm: 120,
    type: "House",
    status: "FOR SALE",
    imageUrl: "https://images.unsplash.com/photo-1568605114967-8130f3a36994?w=600&q=80",
    imageAlt: "Modern white house facade",
    isFeatured: false,
  },
  {
    title: "Urban Loft",
    address: "456 Elm Ave, Portland",
    city: "Portland",
    price: 3200,
    priceType: "rent",
    beds: 1,
    baths: 1,
    sqm: 85,
    type: "Apartment",
    status: "FOR RENT",
    imageUrl: "https://images.unsplash.com/photo-1522708323590-d24dbb6b0267?w=600&q=80",
    imageAlt: "Stylish apartment living room",
    isFeatured: false,
  },
  {
    title: "Highland Retreat",
    address: "789 Mountain Rd, Bend",
    city: "Bend",
    price: 620000,
    priceType: "sale",
    beds: 2,
    baths: 2,
    sqm: 98,
    type: "House",
    status: "FOR SALE",
    imageUrl: "https://images.unsplash.com/photo-1449158743715-0a90ebb6d2d8?w=600&q=80",
    imageAlt: "Cabin in the woods exterior",
    isFeatured: false,
  },
  {
    title: "Sea View Penthouse",
    address: "321 Ocean Dr, Miami",
    city: "Miami",
    price: 4500,
    priceType: "rent",
    beds: 3,
    baths: 3,
    sqm: 180,
    type: "Penthouse",
    status: "FOR RENT",
    imageUrl: "https://images.unsplash.com/photo-1512917774080-9991f1c4c750?w=600&q=80",
    imageAlt: "Bright sea view penthouse bedroom",
    isFeatured: false,
  },
  {
    title: "Central Studio",
    address: "555 Main St, Chicago",
    city: "Chicago",
    price: 550000,
    priceType: "sale",
    beds: 1,
    baths: 1,
    sqm: 50,
    type: "Apartment",
    status: "FOR SALE",
    imageUrl: "https://images.unsplash.com/photo-1493809842364-78817add7ffb?w=600&q=80",
    imageAlt: "Cozy apartment interior",
    isFeatured: false,
  },
  {
    title: "Garden Villa",
    address: "999 Oak Ln, Austin",
    city: "Austin",
    price: 2800,
    priceType: "rent",
    beds: 2,
    baths: 2,
    sqm: 110,
    type: "Villa",
    status: "FOR RENT",
    imageUrl: "https://images.unsplash.com/photo-1600585154340-be6161a56a0c?w=600&q=80",
    imageAlt: "Modern minimalist home exterior with garden",
    isFeatured: false,
  },
  {
    title: "Downtown Studio",
    address: "101 High St, New York",
    city: "New York",
    price: 3200,
    priceType: "rent",
    beds: 1,
    baths: 1,
    sqm: 45,
    type: "Apartment",
    status: "FOR RENT",
    imageUrl: "https://images.unsplash.com/photo-1536376072261-38c75010e6c9?w=600&q=80",
    imageAlt: "Compact modern studio apartment",
    isFeatured: false,
  },
  {
    title: "Lakefront Villa",
    address: "220 Shoreline Dr, Tahoe",
    city: "Lake Tahoe",
    price: 1500000,
    priceType: "sale",
    beds: 4,
    baths: 3,
    sqm: 250,
    type: "Villa",
    status: "FOR SALE",
    imageUrl: "https://images.unsplash.com/photo-1510798831971-661eb04b3739?w=600&q=80",
    imageAlt: "Beautiful villa facing the lake",
    isFeatured: false,
  },
  {
    title: "Sunny Suburb Home",
    address: "77 Maple Ave, Denver",
    city: "Denver",
    price: 450000,
    priceType: "sale",
    beds: 3,
    baths: 2,
    sqm: 160,
    type: "House",
    status: "FOR SALE",
    imageUrl: "https://images.unsplash.com/photo-1513694203232-719a280e022f?w=600&q=80",
    imageAlt: "Cozy suburban home with a green lawn",
    isFeatured: false,
  },
  {
    title: "Skyline Penthouse",
    address: "100 Peak Blvd, San Francisco",
    city: "San Francisco",
    price: 8500,
    priceType: "rent",
    beds: 3,
    baths: 3.5,
    sqm: 300,
    type: "Penthouse",
    status: "FOR RENT",
    imageUrl: "https://images.unsplash.com/photo-1567496898669-ee935f5f647a?w=600&q=80",
    imageAlt: "Luxurious penthouse with city view",
    isFeatured: false,
  },
  {
    title: "Cozy Bungalow",
    address: "44 River Rd, Nashville",
    city: "Nashville",
    price: 350000,
    priceType: "sale",
    beds: 2,
    baths: 1,
    sqm: 90,
    type: "House",
    status: "FOR SALE",
    imageUrl: "https://images.unsplash.com/photo-1464146072230-91cabc968266?w=600&q=80",
    imageAlt: "Small cozy bungalow exterior",
    isFeatured: false,
  },
  {
    title: "Luxury Condo",
    address: "888 Elite Way, Los Angeles",
    city: "Los Angeles",
    price: 6000,
    priceType: "rent",
    beds: 2,
    baths: 2,
    sqm: 140,
    type: "Apartment",
    status: "FOR RENT",
    imageUrl: "https://images.unsplash.com/photo-1515263487990-61b07816b324?w=600&q=80",
    imageAlt: "High-end condo interior",
    isFeatured: false,
  },
  {
    title: "Rustic Cabin",
    address: "12 Pinecone Trail, Aspen",
    city: "Aspen",
    price: 980000,
    priceType: "sale",
    beds: 4,
    baths: 2,
    sqm: 180,
    type: "House",
    status: "FOR SALE",
    imageUrl: "https://images.unsplash.com/photo-1480074568708-e7b720bb3f09?w=600&q=80",
    imageAlt: "Wooden rustic cabin covered in snow",
    isFeatured: false,
  },
  {
    title: "Modern Duplex",
    address: "33 Twin St, Seattle",
    city: "Seattle",
    price: 4500,
    priceType: "rent",
    beds: 3,
    baths: 2,
    sqm: 150,
    type: "House",
    status: "FOR RENT",
    imageUrl: "https://images.unsplash.com/photo-1502005229762-cf1b2da7c5d6?w=600&q=80",
    imageAlt: "Modern duplex architectural design",
    isFeatured: false,
  },
  {
    title: "Historic Townhouse",
    address: "500 Heritage Ln, Boston",
    city: "Boston",
    price: 1200000,
    priceType: "sale",
    beds: 4,
    baths: 3,
    sqm: 220,
    type: "House",
    status: "FOR SALE",
    imageUrl: "https://images.unsplash.com/photo-1512915922686-57c11dde9b6b?w=600&q=80",
    imageAlt: "Classic historic townhouse street view",
    isFeatured: false,
  },
  {
    title: "Beachfront Villa",
    address: "1 Ocean Crest, Malibu",
    city: "Malibu",
    price: 4200000,
    priceType: "sale",
    beds: 5,
    baths: 4,
    sqm: 450,
    type: "Villa",
    status: "FOR SALE",
    imageUrl: "https://images.unsplash.com/photo-1512917774080-9991f1c4c750?w=600&q=80",
    imageAlt: "Stunning beachfront villa pool",
    isFeatured: false,
  },
];

async function main() {
  await prisma.property.deleteMany();

  const usedSlugs = new Set<string>();
  const propertiesWithSlugs = properties.map((p) => {
    const slug = generateUniqueSlug(p.title, usedSlugs);
    usedSlugs.add(slug);
    return { ...p, slug };
  });

  await prisma.property.createMany({ data: propertiesWithSlugs });
  console.log(`Seeded ${properties.length} properties.`);

  await prisma.user.deleteMany();

  const [devHash, adminHash] = await Promise.all([
    bcrypt.hash("Dev12345", 12),
    bcrypt.hash("Admin12345", 12),
  ]);

  await prisma.user.createMany({
    data: [
      {
        name: "Dev User",
        email: "dev@luxe.com",
        passwordHash: devHash,
        role: "user",
      },
      {
        name: "Admin User",
        email: "admin@luxe.com",
        passwordHash: adminHash,
        role: "admin",
      },
    ],
  });

  console.log("Seeded 2 users: dev@luxe.com / admin@luxe.com");
}

main()
  .catch(console.error)
  .finally(() => prisma.$disconnect());
