import type { FeaturedProperty, Property } from "@/types/property";

export const featuredProperties: FeaturedProperty[] = [
  {
    id: "feat-1",
    title: "The Glass Pavilion",
    address: "Beverly Hills, California",
    city: "Beverly Hills",
    price: 5250000,
    priceType: "sale",
    beds: 5,
    baths: 4.5,
    sqm: 4200,
    type: "Villa",
    status: "FOR SALE",
    badge: "Exclusive",
    imageUrl: "https://images.unsplash.com/photo-1600596542815-ffad4c1539a9?w=800&q=80",
    imageAlt: "Luxury modern villa exterior with pool",
  },
  {
    id: "feat-2",
    title: "Azure Heights Penthouse",
    address: "Downtown, Vancouver",
    city: "Vancouver",
    price: 3800000,
    priceType: "sale",
    beds: 3,
    baths: 3,
    sqm: 2100,
    type: "Penthouse",
    status: "FOR SALE",
    badge: "New Arrival",
    imageUrl: "https://images.unsplash.com/photo-1560448204-e02f11c3d0e2?w=800&q=80",
    imageAlt: "Modern interior living room with panoramic view",
  },
];

export const newInMarketProperties: Property[] = [
  {
    id: "new-1",
    title: "Modern Family Home",
    address: "123 Pine St, Seattle",
    city: "Seattle",
    price: 850000,
    priceType: "sale",
    beds: 3,
    baths: 2,
    sqm: 120,
    type: "House",
    status: "FOR SALE",
    imageUrl: "https://images.unsplash.com/photo-1568605114967-8130f3a36994?w=600&q=80",
    imageAlt: "Modern white house facade",
  },
  {
    id: "new-2",
    title: "Urban Loft",
    address: "456 Elm Ave, Portland",
    city: "Portland",
    price: 3200,
    priceType: "rent",
    beds: 1,
    baths: 1,
    sqm: 85,
    type: "Apartment",
    status: "FOR RENT",
    imageUrl: "https://images.unsplash.com/photo-1522708323590-d24dbb6b0267?w=600&q=80",
    imageAlt: "Stylish apartment living room",
  },
  {
    id: "new-3",
    title: "Highland Retreat",
    address: "789 Mountain Rd, Bend",
    city: "Bend",
    price: 620000,
    priceType: "sale",
    beds: 2,
    baths: 2,
    sqm: 98,
    type: "House",
    status: "FOR SALE",
    imageUrl: "https://images.unsplash.com/photo-1449158743715-0a90ebb6d2d8?w=600&q=80",
    imageAlt: "Cabin in the woods exterior",
  },
  {
    id: "new-4",
    title: "Sea View Penthouse",
    address: "321 Ocean Dr, Miami",
    city: "Miami",
    price: 4500,
    priceType: "rent",
    beds: 3,
    baths: 3,
    sqm: 180,
    type: "Penthouse",
    status: "FOR RENT",
    imageUrl: "https://images.unsplash.com/photo-1512917774080-9991f1c4c750?w=600&q=80",
    imageAlt: "Bright sea view penthouse bedroom",
  },
  {
    id: "new-5",
    title: "Central Studio",
    address: "555 Main St, Chicago",
    city: "Chicago",
    price: 550000,
    priceType: "sale",
    beds: 1,
    baths: 1,
    sqm: 50,
    type: "Apartment",
    status: "FOR SALE",
    imageUrl: "https://images.unsplash.com/photo-1493809842364-78817add7ffb?w=600&q=80",
    imageAlt: "Cozy apartment interior",
  },
  {
    id: "new-6",
    title: "Garden Villa",
    address: "999 Oak Ln, Austin",
    city: "Austin",
    price: 2800,
    priceType: "rent",
    beds: 2,
    baths: 2,
    sqm: 110,
    type: "Villa",
    status: "FOR RENT",
    imageUrl: "https://images.unsplash.com/photo-1600585154340-be6161a56a0c?w=600&q=80",
    imageAlt: "Modern minimalist home exterior with garden",
  },
];
